### ISSUE TITLE
Remove the "bbox" parameter when sending a CQL filter to a OGC WFS

### ISSUE THREAD

**Issue by MarioLocati** [INGV/qquake#45] opened 2021-12-07 09:13 UTC
The parameter "bbox" should not be incuded when sending a CQL filter to a WFS service.
The "bbox" parameter should stay when sending a CQL filter to a WMS service.

I tried sending a CQL filter request (Year > 1800) to the WFS "AHEAD-EPICA" and I get the following error

`Layer europe:EPICA_1000_1899: Download of features for layer europe:EPICA_1000_1899 failed or partially failed: WFS exception report (code=OperationProcessingFailed text=bbox and cql_filter both specified but are mutually exclusive). You may attempt reloading the layer with F5`

**Comment by nyalldawson** [comment] 2021-12-07 09:27
Can you check what the source of the loaded layer is for you? (As shown in the first tab on the layer properties dialog).

**Comment by MarioLocati** [comment] 2021-12-07 09:53
Here you are

![image](https://user-images.githubusercontent.com/20398568/145006898-972b04ea-ea0b-4187-9ff3-701ac04f22bb.png)

**Comment by nyalldawson** [comment] 2021-12-07 09:56
Thanks!

**Comment by nyalldawson** [comment] 2021-12-07 11:31
Which QGIS version is this? I can't reproduce (but it may be something which was fixed in QGIS itself)

**Comment by MarioLocati** [comment] 2021-12-07 11:35
![image](https://user-images.githubusercontent.com/20398568/145022180-00851ecb-214b-4f8f-9906-17cfeeb62d9a.png)

**Comment by nyalldawson** [comment] 2021-12-07 11:41
Can you test with 3.22? For me the source loads correctly as `pagingEnabled='true' srsname='EPSG:4326' typename='europe:EPICA_1000_1899' url='https://www.emidius.eu/services/europe/wfs?CQL_FILTER=Year%3E%3D1800.0' version='auto'`

**Comment by MarioLocati** [comment] 2021-12-07 13:15
Just tested with
- QGIS 3.22 on Windows 10
- QGIS 3.10 on Ubuntu 21.10
- QGIS 3.22 on Ubuntu 21.10
and I end up always with the same Python error.

Are you sure you are checking it using the AHEAD-EPICA **WFS** and not the **WMS** service?

**Comment by nyalldawson** [comment] 2021-12-07 21:25
Hmm, still can't reproduce myself! Can you see if https://github.com/INGV/qquake/pull/50 fixes it though?

**Comment by MarioLocati** [comment] 2021-12-08 08:30
No, the commit https://github.com/INGV/qquake/pull/50 did not solve the error for me.

@ghtmtt @robertovallone @GiorgioMariaDeSantis @vlauciani  Could you please try re-installing QQuake by downloading the zip file below and check whether the Python error occurs to you too?
The check requires you to select the AHEAD-EPICA layer from the OGC **WFS** service, apply a filter Year>1800, and then fetch the data.

Here the link to the zip file of the current plugin snapshot for the installation
https://drive.google.com/file/d/1P2JBtOMu0JfLusX_RQD2uJpFkIKe50PB/view?usp=sharing

**Comment by nyalldawson** [comment] 2021-12-08 22:32
@MarioLocati worked it out! I was using an advanced CQL query, and then issue only shows when the basic query editor is used. Fix is on the way :+1:

**Closed as completed** 2021-12-08 23:22 UTC
